{-# LANGUAGE RecursiveDo, StandaloneDeriving, NoMonomorphismRestriction, TupleSections,
             FlexibleContexts, ScopedTypeVariables, ConstraintKinds, TemplateHaskell,
             GADTs, QuasiQuotes, OverloadedStrings #-}

module App (start) where

import qualified Data.Text as T

import Data.Dependent.Map (DMap, fromList)
import Data.Dependent.Sum (DSum( (:=>) ))
import Data.GADT.Compare.TH
import Reflex
import Reflex.Dom.Core
import GHCJS.DOM.Types (JSM)
import qualified Data.Text.Encoding as T
import Lambda
import Parser hiding (value)
import PPrint (Record, pprintdb, pprint)
import Control.Monad (forM_, forM, void)
import Control.Lens
import Data.Char (toUpper)
import Data.List (nub)
import qualified Data.Map as M
import Data.Maybe.HT (toMaybe)
import Data.GADT.Compare
import Missing
import Widgets
import Style (css)

------------------ header -------------------------------------------------------------------------------
header = elClass "h2" "head" $ do
    divClass "matter" $ linkNewTab "https://en.wikipedia.org/wiki/Lambda_calculus" "Lambda Calculus"
    divClass "source" $ linkNewTab "http://github.com/paolino/LambdaCalculus" "source code"


------------- the storing new button widget -----------------
record :: MonadWidget t m => m (Event t String)
record = do
    s <- inputW
    elClass "span" "tooltip" $ text "save to button"
    return $ fmap (map toUpper) s

----------------- a button is an equivalence relation betweena name and an expression
type Button = (String, EC)

---- button definitions as a map (the only acceptable structure for Reflex.DOM ?)
type ButtonsDefs =  [Button]

------------------- the beta reduction widget ----------------
--
-- This is a morphing (dyn) widget: it depends on a pure value and is used
-- inside mapMorph. We cannot return Dynamics here, only m (Event t a); to
-- rely on one event stream we use 'merge', tagging each event with the
-- ReductionE GADT so it can be split back apart with 'pick'/'select'.

-- the three types of event to generated by this widget
data ReductionE a where
    NewButton :: ReductionE Button -- a new button was requested
    NewEdit :: ReductionE EC  -- a text to substitute the expression was requested
    ChangeTactic :: ReductionE Tactic -- a change in evaluation strategy was requested

-- Very handy stuff ,necessary for 'merge'. Write this instances by hand is quadratic in cases on the number of constructor/types
deriveGEq ''ReductionE
deriveGCompare ''ReductionE

-- the input type for the widget
data ReductionInput = ReductionInput
    Tactic -- the state of the tactic is kept outside the widget !! It's recovered here: persistence
    (Maybe ButtonsDefs) -- this is the name substitution store, Nothing says no substitution
    String -- this is the expression at the edit field

-- the schema is input -> m (Event output). We differentiate the morphs with Maybe. First case, there is no
-- output as the expression doesn't parse, Event never is returned.
-- Second case the reduction widget is created and the Event DMap is returned
reductionW :: MonadWidget t m => ReductionInput -> m (Event t (DMap ReductionE Identity))
reductionW (ReductionInput red dbm p) = maybe never id <$> case parsing p of
    Left e -> divClass "edit" $ do
        divClass "title" $ text "Not Parsed"
        elClass "span" "tooltip" . text $ "Use λ or ! or  \\ or / or ^ to open a lambda"
        return Nothing
    Right e -> do
        divClass "edit" $ do
            divClass "title" $ text "Beta reduction"
            r <- divClass "reduction_choice" $ radiocheckW red  [("aggressive",Aggressive) , ("mild",Mild), ("normal",Normal)]
            (bs,es) <- fmap unzip . elClass "ol" "steps" $
                forM (withFreshes var_names $ betas red e) $ \r -> do
                    elClass "li" "steps"  $ do
                        text . T.pack . pprintdb (maybe [] id dbm) $ r
                        b <- elClass "span" "up" $ button "edit"
                        return (r, fmap (const r) b)
            s <- record
            -- creation of the DMap ReductionE Identity tag :=> Event of the right type
            let     b = NewButton :=> fmap (flip (,) (last bs)) s
                    e = NewEdit :=> leftmost es
                    r' = ChangeTactic :=> r
            return . Just . merge $ fromList [b,e,r']

----------------- an initial set of expressions ----------------
--
var_names = nub $ "xyzwnmlkij" ++ ['a' .. 'z']

boot :: ButtonsDefs

boot = [
    ("FALSE",false var_names),
    ("TRUE",true var_names),
    ("AND",and_ var_names),
    ("OR",or_ var_names),
    ("ID",id_ var_names),
    ("ZERO",zero var_names),
    ("SUCC",suc var_names),
    ("PLUS",plus var_names)
    ]


-- expression elements -----------------------------------------
extrabuttons :: MonadWidget t m => m [Event t String]
extrabuttons = mapM (\c -> fmap (const c) <$> button (T.pack c)) ["(" ,"(λ","x" ,"y" ,"z" ,"w" ,"n" ,"m" ,"l" ,"." ,")"]

-- make a button firing an expression
makeButton :: MonadWidget t m => String -> EC -> m (Event t String)
makeButton k v = do
    fmap (pprint . fst) <$> fmap (v ,) <$> button (T.pack k)
--
--
buttonsW :: MonadWidget t m => Dynamic t ButtonsDefs -> m (Event t String)
buttonsW buttonsDef = divClass "standard" $ do

    keys <- extrabuttons
    e <- mapMorph dyn (fmap leftmost . mapM (uncurry makeButton)) buttonsDef
    return . leftmost $ e : keys

----------------- the expression field widget ---------------
--
expressionW :: MonadWidget t m => Event t String -> Event t EC -> m (Dynamic t String,  Dynamic t Bool)
expressionW buttons picked = divClass "edit" $ do
    divClass "title" $ text "Expression"
    c <- divClass "usenames" $ do
        c <- checkbox False def
        elClass "span" "tooltip" $ text "substitute names"
        return c
    b <- divClass "clear" $ button "clear"
    (,view checkbox_value c) <$> divClass "expression" (selInputW buttons (fmap pprint picked) b)


----------------- a dumb footer ---------------------------
--
footer :: MonadWidget t m => m ()
footer = divClass "edit" . divClass "tooltip" $ do
        linkNewTab "https://ghc.gitlab.haskell.org/ghc/doc/users_guide/wasm.html" "GHC Wasm backend"
        text " + "
        linkNewTab "https://reflex-frp.org/" "Reflex"
        text " application. Kudos to them!"

app :: MonadWidget t m => m ()
app = void $ do
    header

    rec buttons <- buttonsW buttonsDef

        (expression, substitute)  <- expressionW  buttons upEC

        -- Dynamic has a real Functor/Applicative instance now, so this is
        -- plain zipDynWith instead of the old app's monadic combineDynWith
        -- shim (which existed because Dynamic didn't have one yet).
        let bf = zipDynWith toMaybe substitute buttonsDef
            f  = zipDynWith ReductionInput redType bf
            bdefsAndExpr = zipDynWith ($) f expression

        reductionE <- mapMorph dyn reductionW bdefsAndExpr

        let     newButton = pick NewButton reductionE
                upEC = pick NewEdit reductionE

        redType <- holdDyn Normal $ pick ChangeTactic reductionE

        buttonsDef <- foldDyn (flip (++) . return) boot newButton

    footer

start :: JSM ()
start = mainWidgetWithCss (T.encodeUtf8 css) app
